package views.subviews;

import views.subviews.TableButton;

import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 * A demo illustrating the embedding of a slider and a button control into a
 * JTable
 * <p/>
 * Copyright (C) 2010 by Ilya Volodarsky
 * <p/>
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * <p/>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p/>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
public class SwingEmbedding extends JFrame 
{
	private static final long serialVersionUID = 6788933562312584275L;

	@SuppressWarnings({ "unchecked", "serial" })
	public SwingEmbedding()
	{
		initComponents();
		
		// important to set the columns that will have embedded elements as "Editable"
		DefaultTableModel model = new DefaultTableModel(new String [] {"Image", "Info", "Action" }, 0) {
	            boolean[] canEdit = new boolean [] {
	                true, true, true
	            };

	            public boolean isCellEditable(int rowIndex, int columnIndex) {
	                return canEdit [columnIndex];
	            }
		};
		table.setModel(model);

		//make first column
		TableColumn buttonColumn = table.getColumnModel().getColumn(0);
		TableButton buttons = new TableButton();
		buttons.addHandler(new TableButton.TableButtonPressedHandler() {

			@Override
			public void onButtonPress(int row, int column) {
				// TODO Auto-generated method stub
				System.out.println("CLICKED1!!!!");
			}
		});
		buttonColumn.setCellRenderer(buttons);
		buttonColumn.setCellEditor(buttons);

		//make second column
		TableColumn buttonColumn12 = table.getColumnModel().getColumn(1);
		TableButton buttons12 = new TableButton();
		buttons12.addHandler(new TableButton.TableButtonPressedHandler() {

			@Override
			public void onButtonPress(int row, int column) {
				// TODO Auto-generated method stub
				System.out.println("CLICKED!!!!");
			}
		});
		buttonColumn12.setCellRenderer(buttons12);
		buttonColumn12.setCellEditor(buttons12);

		//make third column
		TableColumn buttonColumn2 = table.getColumnModel().getColumn(2);
        TableButton buttons2 = new TableButton();
		buttons2.addHandler(new TableButton.TableButtonPressedHandler() {
			
			@Override
			public void onButtonPress(int row, int column) {
				// TODO Auto-generated method stub
				System.out.println("CLICKED2!!!!");
			}
		});

		buttonColumn2.setCellRenderer(buttons2);
		buttonColumn2.setCellEditor(buttons2);
	}

	public void addElement()
	{
		DefaultTableModel model = (DefaultTableModel) table.getModel();	
		model.addRow(new Object[] { "Hi", "Hello", "OK" });
	}

	/**
	 * Initializes components, code generated by NetBeans GUI editor
	 */
	private void initComponents() 
	{
		setTitle("Swing Embedding Demo");
		
		jScrollPane1 = new javax.swing.JScrollPane();
		table = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jScrollPane1.setViewportView(table);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300,
				Short.MAX_VALUE));

		pack();
	}

	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable table;

	public static void main(String[] args) 
	{
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (Exception e) {
			e.printStackTrace();
		} 
		
		SwingEmbedding embedding = new SwingEmbedding();
		embedding.setVisible(true);
		
		embedding.addElement();
		embedding.addElement();
	}

}
